# Generated by Django 2.1.5 on 2026-03-05 20:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimbRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb_date', models.DateField()),
                ('total_meters_climbed', models.IntegerField()),
                ('total_distance', models.IntegerField(help_text='Kilometres')),
                ('completion_time_hours', models.IntegerField()),
                ('star_rating', models.IntegerField(help_text='1 - 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Munro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField(help_text='Metres')),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('difficulty_rating', models.IntegerField(help_text='1 - 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='munro_images/')),
                ('estimated_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='climb_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='munro_app.ClimbRecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteMunro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('munro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to='munro_app.Munro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_munro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_images/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='climbrecord',
            name='munro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_records', to='munro_app.Munro'),
        ),
        migrations.AddField(
            model_name='climbrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
