# Generated by Django 6.0.2 on 2026-02-24 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Munro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.IntegerField(help_text='Metres')),
                ('location', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('difficulty_rating', models.IntegerField(help_text='1 - 5')),
                ('description', models.TextField()),
                ('storage_key', models.CharField(max_length=512)),
                ('content_type', models.CharField(max_length=100)),
                ('estimated_time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimbRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climb_date', models.DateField()),
                ('total_meters_climbed', models.IntegerField()),
                ('total_distance', models.IntegerField(help_text='Kilometres')),
                ('completion_time_minutes', models.IntegerField()),
                ('star_rating', models.IntegerField(help_text='1 - 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('munro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munro_app.munro')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munro_app.climbrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UserFavouriteMunro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('munro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='munro_app.munro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
