# Generated by Django 6.0.2 on 2026-03-13 22:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munro',
            name='difficulty_rating',
            field=models.IntegerField(blank=True, help_text='1 - 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='munro',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
