# Generated by Django 6.0.2 on 2026-03-01 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbrecord',
            name='munro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_records', to='munro_app.munro'),
        ),
        migrations.AlterField(
            model_name='climbrecord',
            name='star_rating',
            field=models.IntegerField(help_text='1 - 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='climbrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climb_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='munro',
            name='difficulty_rating',
            field=models.IntegerField(help_text='1 - 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='photo',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='munro_app.climbrecord'),
        ),
        migrations.AlterField(
            model_name='userfavouritemunro',
            name='munro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to='munro_app.munro'),
        ),
        migrations.AlterField(
            model_name='userfavouritemunro',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_munro', to=settings.AUTH_USER_MODEL),
        ),
    ]
