# Generated by Django 6.0.2 on 2026-03-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0002_alter_climbrecord_munro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='climbrecord',
            old_name='completion_time_minutes',
            new_name='completion_time_hours',
        ),
    ]
