# Generated by Django 6.0.2 on 2026-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0002_alter_munro_difficulty_rating_alter_munro_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='munro_images/'),
        ),
    ]
