# Generated by Django 6.0.2 on 2026-03-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0003_alter_munro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munro',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
