# Generated by Django 2.1.5 on 2026-03-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0002_alter_climbrecord_id_alter_munro_id_alter_photo_id_and_more'),
        ('munro_app', '0004_alter_munro_description'),
    ]

    operations = [
    ]
