# Generated by Django 6.0.1 on 2026-03-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munro_app', '0005_merge_20260315_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbrecord',
            name='completion_time_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='climbrecord',
            name='total_distance',
            field=models.FloatField(help_text='Kilometres'),
        ),
        migrations.AlterField(
            model_name='climbrecord',
            name='total_meters_climbed',
            field=models.FloatField(),
        ),
    ]
